name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
              username: flamekaiserr
              password: Rohitr@o14


      - name: Build and push Docker image
        run: |
          docker build -t flamekaiserr/my-python-app:${{ github.sha }} .
          docker push flamekaiserr/my-python-app:${{ github.sha }}
